server:
  port: 8888

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/relidaning/mySpringcloud-netflix.git
          search-paths: configuration