server:
  port: 8888

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/relidaning/mySpringcloud-netflix.git
          default-label: main
          search-paths: configuration
          skip-ssl-validation: true
          basedir: target/configuration
#          username: 453882101@qq.com
#          password: eqbq0723@git

eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'debug'