server:
  port: 8888

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/relidaning/mySpringcloud-netflix.git
          search-paths: configuration
          skip-ssl-validation: true
          basedir: target/config
#          username: 453882101@qq.com
#          password: eqbq0723@git

eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false