server:
  port: 8070

spring:
  application:
    name: zuul
  cloud:
    config:
      uri: http://82.157.147.8:8888/

zuul:
  routes:
    demo:
      path: /demo/**
      url: 82.157.147.8:8080
  ignored-services: admin, eureka6

eureka:
  instance:
    hostname: 82.157.147.8
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka
    fetch-registry: false
