server:
  port: 8080

spring:
  application:
    name: demo
  cloud:
    config:
      uri: http://82.157.147.8:8888/

local:
  mail: lidaning@163.com
  nickName: lidaning

info:
  mail: shakeit@126.com
  nickName: shakeit