server:
  port: 8080

spring:
  application:
    name: demo
  cloud:
    config:
      uri: http://82.157.147.8:8888/

local:
  mail: lidaning@163.com
  nickName: lidaning

eureka:
  instance:
    hostname: 82.157.147.8
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka
    fetch-registry: false