server:
  port: 8761

spring:
  application:
    name: eureka
  cloud:
    config:
      uri: http://localhost:8888/

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#    fetch-registry: false
#    registerWithEureka: false
