spring:
  #  profiles:
  #    active: dev
  cloud:
    config:
      uri: http://localhost:8888/
#  datasource:
#    url: jdbc:oracle:thin:@192.168.178.128:1521/xe
#    username: lidaning
#    password: lidaning
#  redis:
#    host: 192.168.178.128
#    port: 6379
#    password:
#    pool:
#      max-active: -1
#      max-wait: -1

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show_details: always

jwt:
  HEADER: Authorization
  SECRET: a2c4e6g8i0k
  TIMEOUT: 60000
  ISSUE: lidaning

zuul:
  sensitive-headers: Set-Cookie,Cookie,Host,Connection,Content-Length,Content-Encoding,Server,Transfer-Encoding,X-Application-Context
