mySpringcloud-netflix:
  server:
    ip: 127.0.0.1

spring:
  #  profiles:
  #    active: dev
  cloud:
    inetutils.preferred-networks: ${mySpringcloud-netflix.server.ip}
#    config:
#      uri: http://${mySpringcloud-netflix.server.ip}:8888/
#  datasource:
#    url: jdbc:oracle:thin:@192.168.178.128:1521/xe
#    username: lidaning
#    password: lidaning
#  redis:
#    host: 192.168.178.128
#    port: 6379
#    password:
#    pool:
#      max-active: -1
#      max-wait: -1

eureka:
  instance:
    hostname: ${mySpringcloud-netflix.server.ip}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show_details: always

jwt:
  HEADER: Authorization
  SECRET: a2c4e6g8i0k
  TIMEOUT: 60000
  ISSUE: lidaning

#zuul:
#  sensitive-headers: Set-Cookie,Cookie,Host,Connection,Content-Length,Content-Encoding,Server,Transfer-Encoding,X-Application-Context

info:
  mail: shake@config-app.yml
  nickName: shake

logging:
  file: ./log/${spring.application.name}.log
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"

